import type { Lang } from '@/lib/types';

const en = {
  illustration: 'Illustrated AI coworker', directory: 'Meet the agents', customize: 'Make this agent yours.',
  introduction: 'The skills and specialist workflows are included. Add your context, then review connections and deployment in your workspace.',
  yourContext: 'Your working brief', included: 'Included in this package', skills: 'Skills', workers: 'Specialists', connections: 'Connections', workflows: 'Workflows',
  method: 'Working method', outputs: 'What you receive', checks: 'Quality checks', handoff: 'Handoff', approval: 'Your control',
  contentLanguage: 'The detailed operating instructions are currently in English.',
  name: 'Agent name', organization: 'Company or work context', organizationHint: 'For example, your company, audience, or target industry.',
  goals: 'What should they work toward?', goalsHint: 'Describe the first outcome you want. You can leave this blank and provide a brief later.',
  instructions: 'Additional instructions', instructionsHint: 'Add preferences or context. Keep passwords and API keys out of this brief. Privacy and approval rules still apply.',
  tone: 'Communication style', professional: 'Professional', warm: 'Warm', concise: 'Concise', harness: 'Run with', harnessHint: 'Choose a runtime. Availability is checked separately before deployment.',
  save: 'Save agent package', saving: 'Saving your package…', noCharge: 'Saves a configured draft. This step does not deploy an agent or charge credits.',
  saveError: 'Your package could not be saved. Please try again.', signIn: 'Sign in', signInHint: 'Sign in in a new tab, then try again. Your brief is still here.',
  forbidden: 'You do not have permission to manage this agent. Ask your workspace administrator for access.',
  package: 'Agent package', saved: 'Saved draft', deploying: 'Deployment pending', failed: 'Deployment needs attention', ready: 'Package installed',
  loading: 'Loading package details…', loadError: 'Package details could not be loaded. Retry to check the current state.', retry: 'Retry', refresh: 'Refresh status',
  savedHint: 'Your instructions and skills are saved. Installation and connections are confirmed by the runtime before this agent can run.',
  readyHint: 'Installation and required connections are confirmed. The agent is paused until an execution service is available.',
  pendingHint: 'Deployment has been requested. Refresh to check for a confirmed result.',
  unavailable: 'Deployment is not enabled here yet. Your package is saved; your workspace administrator can enable a compatible runtime.',
  unsupported: 'The deployment service does not support this runtime yet. Your configured package remains saved.',
  deploy: 'Deploy agent', deployingAction: 'Requesting deployment…', deployError: 'Deployment could not be confirmed. Refresh the status before trying again.',
  download: 'Download package', downloading: 'Preparing download…', downloadError: 'The package could not be downloaded. Please try again.',
  installed: 'Skills installed', configured: 'Configured skills', required: 'Required', optional: 'Optional', connected: 'Connected', missing: 'Missing', unverified: 'Not verified',
  connectionHint: 'Connection status comes from the runtime. Saving this package does not connect your accounts.',
  version: 'Version', viewPackage: 'Explore the package', capabilityIntro: 'A working method is included for each task, with specialist roles and clear handoffs.',
};

export const packageCopy: Record<Lang, typeof en> = {
  en,
  zh: {
    illustration: 'AI 搭档插画', directory: '认识智能体', customize: '让这位搭档适合你。', introduction: '技能和专员工作流程已包含在内。补充你的工作背景，再到工作区查看连接和部署状态。',
    yourContext: '你的工作简报', included: '此套件包含', skills: '技能', workers: '专员', connections: '连接', workflows: '工作流程', method: '工作方法', outputs: '交付内容', checks: '质量检查', handoff: '交接内容', approval: '由你掌控', contentLanguage: '详细的操作说明目前为英文。',
    name: '智能体名称', organization: '公司或工作背景', organizationHint: '例如你的公司、目标受众或行业。', goals: '希望它达成什么目标？', goalsHint: '描述你最先想要的成果，也可以稍后再提供简报。', instructions: '补充说明', instructionsHint: '补充偏好或背景。请勿填写密码或 API 密钥。隐私和审批规则仍然适用。',
    tone: '沟通风格', professional: '专业', warm: '亲切', concise: '简洁', harness: '运行方式', harnessHint: '选择运行环境，部署前会单独检查可用性。', save: '保存智能体套件', saving: '正在保存套件…', noCharge: '此步骤仅保存配置草稿，不会部署智能体或扣除积分。', saveError: '无法保存套件，请重试。', signIn: '登录', signInHint: '请在新标签页登录后重试，你填写的简报仍保留在这里。', forbidden: '你没有管理此智能体的权限，请联系工作区管理员。',
    package: '智能体套件', saved: '已保存草稿', deploying: '等待部署确认', failed: '部署需要处理', ready: '套件已安装', loading: '正在读取套件…', loadError: '无法读取套件详情，请重试以查看当前状态。', retry: '重试', refresh: '刷新状态',
    savedHint: '说明和技能已保存。运行环境确认安装和所需连接后，智能体才能运行。', readyHint: '套件安装和所需连接已确认。智能体处于暂停状态，等待执行服务可用。', pendingHint: '已请求部署，请刷新以查看确认结果。', unavailable: '此处尚未启用部署。套件已保存，工作区管理员可启用兼容的运行环境。', unsupported: '部署服务暂不支持此运行方式，配置好的套件仍已保存。',
    deploy: '部署智能体', deployingAction: '正在请求部署…', deployError: '无法确认部署结果，请先刷新状态再重试。', download: '下载套件', downloading: '正在准备下载…', downloadError: '无法下载套件，请重试。', installed: '已安装技能', configured: '已配置技能', required: '必需', optional: '可选', connected: '已连接', missing: '未连接', unverified: '尚未验证', connectionHint: '连接状态由运行环境确认，保存套件不会连接你的账号。', version: '版本', viewPackage: '查看套件', capabilityIntro: '每项任务均配有工作方法、专员分工和明确的交接流程。',
  },
  zht: {
    illustration: 'AI 搭檔插畫', directory: '認識智慧體', customize: '讓這位搭檔適合你。', introduction: '技能和專員工作流程已包含在內。補充你的工作背景，再到工作區查看連接和部署狀態。',
    yourContext: '你的工作簡報', included: '此套件包含', skills: '技能', workers: '專員', connections: '連接', workflows: '工作流程', method: '工作方法', outputs: '交付內容', checks: '品質檢查', handoff: '交接內容', approval: '由你掌控', contentLanguage: '詳細的操作說明目前為英文。',
    name: '智慧體名稱', organization: '公司或工作背景', organizationHint: '例如你的公司、目標受眾或產業。', goals: '希望它達成什麼目標？', goalsHint: '描述你最先想要的成果，也可以稍後再提供簡報。', instructions: '補充說明', instructionsHint: '補充偏好或背景。請勿填寫密碼或 API 金鑰。隱私和審批規則仍然適用。',
    tone: '溝通風格', professional: '專業', warm: '親切', concise: '簡潔', harness: '執行方式', harnessHint: '選擇執行環境，部署前會單獨檢查可用性。', save: '儲存智慧體套件', saving: '正在儲存套件…', noCharge: '此步驟僅儲存設定草稿，不會部署智慧體或扣除點數。', saveError: '無法儲存套件，請重試。', signIn: '登入', signInHint: '請在新分頁登入後重試，你填寫的簡報仍保留在這裡。', forbidden: '你沒有管理此智慧體的權限，請聯絡工作區管理員。',
    package: '智慧體套件', saved: '已儲存草稿', deploying: '等待部署確認', failed: '部署需要處理', ready: '套件已安裝', loading: '正在讀取套件…', loadError: '無法讀取套件詳情，請重試以查看目前狀態。', retry: '重試', refresh: '重新整理狀態',
    savedHint: '說明和技能已儲存。執行環境確認安裝和所需連接後，智慧體才能運作。', readyHint: '套件安裝和所需連接已確認。智慧體處於暫停狀態，等待執行服務可用。', pendingHint: '已請求部署，請重新整理以查看確認結果。', unavailable: '此處尚未啟用部署。套件已儲存，工作區管理員可啟用相容的執行環境。', unsupported: '部署服務暫不支援此執行方式，設定好的套件仍已儲存。',
    deploy: '部署智慧體', deployingAction: '正在請求部署…', deployError: '無法確認部署結果，請先重新整理狀態再重試。', download: '下載套件', downloading: '正在準備下載…', downloadError: '無法下載套件，請重試。', installed: '已安裝技能', configured: '已設定技能', required: '必要', optional: '選用', connected: '已連接', missing: '未連接', unverified: '尚未驗證', connectionHint: '連接狀態由執行環境確認，儲存套件不會連接你的帳號。', version: '版本', viewPackage: '查看套件', capabilityIntro: '每項任務均配有工作方法、專員分工和明確的交接流程。',
  },
  ja: {
    illustration: 'AI パートナーのイラスト', directory: 'エージェントを見る', customize: 'あなたの仕事に合わせる。', introduction: 'スキルと専門担当のワークフローは含まれています。仕事の背景を加え、ワークスペースで接続とデプロイを確認しましょう。',
    yourContext: '仕事の依頼内容', included: 'パッケージに含まれるもの', skills: 'スキル', workers: '専門担当', connections: '接続', workflows: 'ワークフロー', method: '仕事の進め方', outputs: '成果物', checks: '品質チェック', handoff: '引き継ぎ', approval: 'あなたの権限', contentLanguage: '詳細な実行手順は現在、英語で提供しています。',
    name: 'エージェント名', organization: '会社・仕事の背景', organizationHint: '会社、対象者、業界などを記入してください。', goals: 'どんな成果を目指しますか？', goalsHint: '最初にほしい成果を記入してください。後から依頼することもできます。', instructions: '追加の指示', instructionsHint: '希望や背景を追加できます。パスワードや API キーは入力しないでください。プライバシーと承認のルールは引き続き適用されます。',
    tone: '話し方', professional: 'プロフェッショナル', warm: '親しみやすい', concise: '簡潔', harness: '実行環境', harnessHint: '実行環境を選択してください。デプロイ前に利用可否を確認します。', save: 'パッケージを保存', saving: '保存しています…', noCharge: '設定の下書きだけを保存します。この操作でデプロイやクレジットの請求は行いません。', saveError: '保存できませんでした。もう一度お試しください。', signIn: 'ログイン', signInHint: '新しいタブでログインしてから再試行してください。入力内容はこのまま残ります。', forbidden: 'このエージェントを管理する権限がありません。管理者に確認してください。',
    package: 'エージェントパッケージ', saved: '下書きを保存済み', deploying: 'デプロイ確認待ち', failed: 'デプロイの確認が必要', ready: 'パッケージをインストール済み', loading: 'パッケージを読み込み中…', loadError: '詳細を読み込めませんでした。再試行して現在の状態を確認してください。', retry: '再試行', refresh: '状態を更新',
    savedHint: '指示とスキルは保存済みです。実行環境でインストールと必要な接続が確認されてから実行できます。', readyHint: 'インストールと必要な接続を確認しました。実行サービスが利用可能になるまでエージェントは一時停止中です。', pendingHint: 'デプロイをリクエストしました。状態を更新して結果を確認してください。', unavailable: 'ここではまだデプロイを利用できません。パッケージは保存済みです。管理者が対応する実行環境を有効にできます。', unsupported: 'デプロイサービスはこの実行環境にまだ対応していません。設定は保存されています。',
    deploy: 'エージェントをデプロイ', deployingAction: 'デプロイをリクエスト中…', deployError: 'デプロイを確認できませんでした。状態を更新してから再試行してください。', download: 'パッケージをダウンロード', downloading: 'ダウンロードを準備中…', downloadError: 'ダウンロードできませんでした。再試行してください。', installed: 'インストール済みスキル', configured: '設定済みスキル', required: '必須', optional: '任意', connected: '接続済み', missing: '未接続', unverified: '未確認', connectionHint: '接続状態は実行環境が確認します。保存だけではアカウントは接続されません。', version: 'バージョン', viewPackage: 'パッケージを見る', capabilityIntro: '各タスクの手順、専門担当の役割、引き継ぎ方法を用意しています。',
  },
};
